### ISSUE TITLE
agent can not handle syslog entries for error_log and access_log in nginx configuration

### ISSUE THREAD

**Issue by defanator** [nginx/agent#185]
When either error_log or access_log are configured with [syslog logging](https://nginx.org/en/docs/syslog.html), agent treats syslog arguments as a file name and throws the error:

```
time="2023-01-27T05:45:46Z" level=warning msg="NGINX Access log syslog:server=127.0.0.1,nohostname,tag=nginx_access is not readable or is disabled. Please make it readable and enabled in order for NGINX metrics to be collected."
time="2023-01-27T05:45:46Z" level=warning msg="NGINX Error log syslog:server=127.0.0.1,nohostname,tag=nginx_error is not readable or is disabled. Please make it readable and enabled in order for NGINX metrics to be collected."
```

**Comment by Dean-Coakley** [comment]
Thanks for the bug report @defanator 

I'll ensure this gets resolved for you shortly.

**Comment by Retssaze** [comment]
Is it being solved now?

**Comment by Dean-Coakley** [comment]
Sure.

Let us know if you need any assistance.

**Comment by Retssaze** [comment]
Deal

**Comment by zsteinkamp** [comment]
Hey @Retssaze! Zack from NGINX here. We have a team here who has also encountered this issue and is interested in a fix, and so I was wondering if there was any assistance I can give to you on this? If life has gotten busy or if the problem is bigger than it looked, just let me know here too. Thanks!

**Comment by Retssaze** [comment]
Dear Zack! @zsteinkamp

thank you for the mail. It is always busy. I should expedite my efforts!

**Comment by zsteinkamp** [comment]
Thanks @Retssaze :) I'll check back in here in a week. In the meantime, I'm more than happy to talk through ideas or approaches with you.

**Comment by Retssaze** [comment]
Dear Zack,

I have found something, the singular thing so far please tell where and in what configuration file to enable syslog at agent?

**Comment by zsteinkamp** [comment]
Hi @Retssaze -- it is the main NGINX configuration file, located at `/etc/nginx/nginx.conf`.

Its contents should look like this:
```
worker_processes  1;

events {
  worker_connections  1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  log_format  main_ext  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        '"$host" sn="$server_name" '
                        'rt=$request_time '
                        'ua="$upstream_addr" us="$upstream_status" '
                        'ut="$upstream_response_time" ul="$upstream_response_length" '
                        'cs=$upstream_cache_status' ;

  # THE IMPORTANT LINE IS BELOW
  access_log syslog:server=127.0.0.1:12000,tag=amplify,severity=info main_ext;

  server {
    listen 80;

    location /nginx_status {
      stub_status on;
      allow 127.0.0.1;
      deny all;
    }

    location / {
    }
  }
}
```

What was the thing you found?

**Comment by Retssaze** [comment]
Dear Zack,

thank you very much for the mail!
I have solved one bug along the way and almost completed the task

Should the whole NGINX be run here for tests with this config?



пн, 3 апр. 2023 г. в 17:57, Zack Steinkamp ***@***.***>:

**Comment by zsteinkamp** [comment]
Great!
I think it's only necessary for this bug to test with the Agent.

You can validate that your `nginx.conf` is in the correct format by running `nginx -t`, so if you are including nginx configuration in a test case, you can use that to verify that you are using a valid config file.

**Comment by Dean-Coakley** [comment]
@Retssaze The goal is that when the nginx config uses a `syslog:` target that is not interpreted as a file path in error. Which leads to the agent logging that it is not readable.

In order to handle this case you will likely have to handle this kind of input in both:
* https://github.com/nginx/agent/blob/main/src/core/metrics/sources/nginx_error_log.go
* https://github.com/nginx/agent/blob/main/src/core/metrics/sources/nginx_access_log.go

You can find more information about the `access_log` and `error_log` directives and available parameters: 
* https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log 
* https://nginx.org/en/docs/ngx_core_module.html#error_log

And some examples of what logging to a syslog location looks like: https://nginx.org/en/docs/syslog.html

**Comment by Retssaze** [comment]
@Dean-Coakley @zsteinkamp The question is whether it needs to parse the syslog in result?

**Comment by Dean-Coakley** [comment]
@Retssaze No, there is no requirement to parse the syslog configuration.

**Comment by Retssaze** [comment]
Thank you Very Much!
