### ISSUE TITLE
Agent doesn't handle hostnames with special characters

### ISSUE THREAD

**Issue by m-bers** [nginx/agent#274]
I have an NGINX instance with hostname `test-example.com`
I tried deploying the nginx-agent package using the curl script from my NMS host, and the agent starts successfully. I can see instance details under Instance Manager -> Instances, but when I try to edit the configuration, it gives this error:
```
Oops. Something went wrong.
URIError: malformed URI sequence
```

If I change the hostname to something without special characters (e.g. `testexample.com`), everything works fine.

**Comment by oCHRISo** [comment]
Thanks @m-bers for opening this issue. The NGINX Management Suite has since released (April 6th) a fix for this issue in version 2.9.1. To resolve the issue, you will need to upgrade NMS to 2.9.1. There isn't any need to change the NGINX Agent version.
(details here https://docs.nginx.com/nginx-management-suite/nim/releases/release-notes/#291) 

Closing this issue. Thanks again for your time @m-bers
