### ISSUE TITLE
Bypass Nginx Cache

### ISSUE THREAD

**Issue by AyushBhardwaj321** [nginx/agent#322]
Hello,
I am hosting web app using Nginx and setting up static file in nginx directory. It is getting executed and hosted successfully.
When in new push i am building React application and saving files in nginx directory, then it is showing me **blank white page**, it will be because of the cookies saved in browser. When i am using **CTRL + F5** (refreshes the page by clearing the cached content of the page) then i am able to see site.
1. Is there a way i can remove browzer cookies through nginx ? If yes, how to do that.
2. Is there a way that i can pass request to origin server everytime? If yes, how to do that.
Is there any other way please let me know.
Thanks in advance

**Comment by oCHRISo** [comment]
Hi @AyushBhardwaj321,

Thanks very much for your question. While this repository is focused at the NGINX Agent product we will be happy to help direct you to the best place to find the answers to your questions. Please join us on our NGINX Community Slack (Link below), the #nginx-users channel would be the best place for asking and answering questions about NGINX. 

1. Based on your question you're looking to ensure the web browser doesn't store anything in cache. This can be done by removing all headers related to cache from the response of the HTTP request. Below can be added to your NGINX configuration. 

`
add_header Last-Modified $date_gmt;
add_header Cache-Control 'no-store, no-cache';
if_modified_since off;
expires off;
etag off;
` 

2. For this question there is more information (NGINX configuration) needed to be better understand how to achieve your desired solution.

Please connect with us on our NGINX Community Slack so that we can help you achieve your desired solution.
https://nginxcommunity.slack.com/archives/C02T18NMZU4

Chat soon and all the best,
NGINX Agent team

**Comment by oCHRISo** [comment]
We are closing this issue. 
Thanks very much, @AyushBhardwaj321
