### ISSUE TITLE
grpc and http cannot successfully listen to port

### ISSUE THREAD

**Issue by happydogggg** [nginx/agent#609]
Why does the command keep running after entering go run sdk/examples/server.go but does not succeed?
![Xshell_wXuCgASsX6](https://github.com/nginx/agent/assets/128985403/1db58fa6-f71f-4392-a4e6-147bbfe09c73)

**Comment by oliveromahony** [comment]
hi @happydogggg 

Thanks for creating the issue. I ran the example server locally for me and got the following:

```
go run sdk/examples/server.go 
INFO[0000] http listening                               
INFO[0000] gRPC listening
```

The server.go uses the following hardcoded values https://github.com/nginx/agent/blob/main/sdk/examples/server.go#L27 since it is for example Management Servers only. You may need to add these ports 54789 and 54790 to your firewall rules to allow them or change these values to allow ports that you allow. 

Please let me know if you have any other questions
